@startuml
|Cư dân|
start
:1. Thông báo mất thẻ;
|Nhân viên|
:2. Hướng dẫn điền form thông tin;
|Cư dân|
repeat :3. Điền form;
:4. Nộp form;
|Cư dân|
|Hệ thống|
if (Kiểm tra thông tin) then (Không hợp lệ)
    :5. Thông báo bảo vệ;
    :6. Thông báo khách hàng điền sai thông tin;
else (Hợp lệ)
    :7. Hủy Id thẻ cũ;
    :8. Tạo thẻ mới;
endif
repeat while (Kiểm tra thông tin) is (Không hợp lệ) not (Hợp lệ)
:9. Thông báo bảo vệ;
:10. Thông báo khách hàng;
|Nhân viên|
:11. Đưa thẻ cho khách hàng;
stop
@enduml