@startuml
|Khách của cư dân|
|Cư dân|
:1. Yêu cầu thêm thẻ ra vào cho User1;
|Nhân viên|
:2. Yêu cầu đưa ra thông tin thẩm quyền;
|Cư dân|
:3. Cung cấp thông tin;
|Nhân viên|
if(Kiểm tra thông tin của người bảo hộ) then (Không hợp lệ)
:4. Từ chối tiếp nhận;
stop
else (Hợp lệ)
:5. Yêu cầu cung cấp thông tin khách;
|Khách của cư dân|
:6. Cung cấp thông tin;
|Nhân viên|
:7. Nạp thông tin vào thẻ mới;
|Hệ thống|
:8. Nạp thông tin;
endif
|Nhân viên|
:10. Gửi thẻ cho khách hàng;
stop
@enduml