@startuml
class CheckPoint{
    - checkPointId: string
    - location: string
    - installationDate: Datetime
    - active: bool
    - upTime: float
    - entityId: string
    + entry(string userId)
    + openOnce()
    + open(string: EntranceId)
    + close()
}
class Guest{
    - guestId: string
    - name: string
    - purpose: string
    - date: Datetime
    - expirationDate: Datetime
    - allower: userId
    - urlIdPicture: string
    - entranceId: string
    + prolonged(float timeBySec)
    + revokeAccess()
}
class Entrance{
    - entranceId: string
    + addEntrance(MinorEntrance Entrance)
    + removeEntrance(MinorEntrance Entrance)
}
class MinorEntrance{
    - entranceId: string
    - checkpointId: string
}
Entrance "1"--"1*" MinorEntrance
CheckPoint "1"--"1*" MinorEntrance
Guest "*"--"1" Entrance

@enduml