class Receipt{
  - receiptID: string
  - creator: string
  - customers: List<string>
  - reason: string
  - title: string
  - fee: float
}
class Pay{
  - receiptID: string
  - datePay: Datetime
  - method: string
  - receipt: string
  - residentID: string
}
Pay "*"--"1"Receipt
Resident "1"--"*"Pay
Resident "*"--"*"Receipt