class Service{
  - type: ServiceType
  - detail: string
  - dateRequest: Datetime
  - dateApprove: Datetime
  - dateDeliver: Datetime
  - dateFinished: Datetime
  - fee: float
  - isApproved: bool
  - approvedBy: string
  - customerID: string
  - appartmentID: string
  - isAbort: bool
  - workerID: List<string>
  + approve(List<string> workers,Datetime dateWork, float fee,string approvedBy)
  + deny(string reason)
}
enum ServiceType{
  - Fix
  - CleanHouse
  - Laundry
  - Transport
}
class Rate{
  - serviceID: string
  - residentID: string
  - star: byte
  - comment: string
}