@startuml


class "Resident" {
  -residentID: string
  -name: string
  -phoneNumber: string
  -password: string
  +changePassword(string newPass)
}

class Apartment {
  -apartmentID: string
  -apartmentNumber: string
  -floor: int
  -numberOfRooms: int
  -masterResidentID: string
  -memberList: List<Member>
  +addMember(Member member)
  +changeMaster(string residentID)
}

class Announcement {
  -announcementID: string
  -title: string
  -content: string
  -date: Date
  -fileAttachedURL: List<String>
}


Resident "*"--"*" Apartment

@enduml
