class Service{
  - type: ServiceType
  - detail: string
  - dateRequest: Datetime
  - dateApprove: Datetime
  - dateDeliver: Datetime
  - dateFinished: Datetime
  - fee: float
  - isApproved: bool
  - approvedBy: string
  - customerID: string
  - appartmentID: string
  - workerID: List<string>
  + approve(List<string> workers,Datetime date, float fee)
  + deny(string reason)
}
enum ServiceType{
  - Fix
  - CleanHouse
  - Laundry
  - Transport
}