@startuml
left to right direction

actor Customer as C
actor Staff as S
rectangle ECommerceSystem {
  usecase "Browse Products" as UC1
  usecase "View Promotions" as UC2
  usecase "Make Online Purchase" as UC3
  usecase "Make In-Store Purchase" as UC4
  usecase "Receive Goods at Store" as UC5
  usecase "Use Delivery Service" as UC6
}

rectangle BusinessManagement {
  usecase "Manage Stock" as UC7
  usecase "Manage Orders" as UC8
  usecase "Manage Delivery Status" as UC9
  usecase "Manage Payments" as UC10
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4
C --> UC5
C --> UC6
S --> UC7
S --> UC8
S --> UC9
S --> UC10
@enduml
