@startuml

|Admin|
start
:Chọn module "Căn hộ";
|Website admin|
: Hiển thị danh sách căn hộ;
|Admin|
:Chọn button "Thêm căn hộ";
|Website admin|
repeat  
:Hiển thị popup "Thêm căn hộ";
|Admin|
:Nhập thông tin căn hộ, chủ hộ, sđt,...;
|Website admin|
repeat while (Tạo thành công?) is (no) not (yes);
:Hiển thị thông báo "Tạo thành công;
:Tự động gửi mã căn hộ và "Hướng dẫn tải app cư dân" qua SMS sđt cho chủ hộ;
|Cư dân|
:Tải app dành cho cư dân;
:Đăng kí tài khoản;
|App cư dân|
:Hiển thị thông báo "Chờ ban quản lý duyệt tài khoản";
|Admin|
:Chọn module "cư dân";
|Website admin|
:Hiển thị danh sách cư dân;
|Admin|
if (Xác nhận?) then (yes)
    :Nhấn xác nhận "Duyệt" tài khoản cư dân cần duyệt;
else (no)
    :Nhấn "Từ chối" tài khoản cư dân cần duyệt;
endif
|Website admin|
:Tự động gửi SMS thông báo đến sđt cư dân đã đăng kí;
|Cư dân|
:Đăng nhập tài khoản;
stop
@enduml