@startuml

participant Quanly

participant "Hệ thống" as System
participant Cudan


activate System
Quanly -> System: 1. Chọn hợp đồng
Quanly -> System: 2. Tạo yêu cầu gia hạn hợp đồng
Quanly -> System: 3.Chọn thời hạn
activate Cudan
System -> Cudan: 4. Gửi hợp đồng cho đối tác
Cudan -> Cudan: 5. Kiểm tra thông tin

alt Chấp nhận
Cudan --> System: 5a1. Gửi thông báo chấp nhận cho quản lý
System--> Quanly: 5a2. Ký eSignature

System-> Cudan: 5a3. Ký eSignature

else Không chấp nhận
    Cudan --> System: 5b1.Gửi thông báo yêu cầu đã bị từ chối cho Quản lý
    deactivate Cudan
end
System -> System: 6. Lưu data
System -> Quanly: 7. Thông báo gia hạn thành công

System -> Cudan: 8. Thông báo gia hạn thành công
deactivate System
@enduml
