@startuml

participant Quanly

participant "Hệ thống" as System
participant Cudan


activate System
Quanly -> System: 1. Chọn hợp đồng
Quanly -> System: 2. Tạo yêu cầu gia hạn hợp đồng
Quanly -> System: 3.Chọn thời hạn
NhanVien -> System: 4. Chọn button "Tạo thông báo phí"
System -> System: 5. Hiển thị popup "Tạo thông báo phí"
NhanVien -> System: 6. Nhập thông tin thông báo phí và nhấn "Gửi thông báo"
System -> CSDL: 7. Kiểm tra gửi thành công

alt Gửi thành công
activate CSDL
     CSDL --> System: 8. Hiển thị thông báo "Gửi thông báo thu phí thành công" 


else Gửi không thành công 
    CSDL --> System: 9. Hiển thị thông báo "Lỗi!!"
    deactivate CSDL 
    System -> System: 10. Hiển thị popup "Tạo thông báo phí"
end

deactivate System
@enduml
