@startuml

participant "Quản lý"

participant "Hệ thống" as System
participant "Cư dân"


activate System
"Quản lý" -> System: 1. Chọn hợp đồng
"Quản lý" -> System: 2. Tạo yêu cầu gia hạn hợp đồng
"Quản lý" -> System: 3.Chọn thời hạn
activate "Cư dân"
System -> "Cư dân": 4. Gửi hợp đồng cho đối tác
"Cư dân" -> "Cư dân": 5. Kiểm tra thông tin

alt Chấp nhận
"Cư dân" --> System: 5a1. Gửi thông báo chấp nhận cho quản lý
System--> "Quản lý": 5a2. Ký eSignature

System-> "Cư dân": 5a3. Ký eSignature

else Không chấp nhận
    "Cư dân" --> System: 5b1.Gửi thông báo yêu cầu đã bị từ chối cho Quản lý
    deactivate "Cư dân"
end
System -> System: 6. Lưu data
System -> "Quản lý": 7. Thông báo gia hạn thành công

System -> "Cư dân": 8. Thông báo gia hạn thành công
deactivate System
@enduml
