@startuml

participant "Quản lý"
participant "Nhân viên"
participant "Hệ thống" as System


"Quản lý" -> "Quản lý": 1. Công bố quyết định kiểm kê

"Quản lý"-> System: 2. Thành lập danh sách nhân viên làm hội đồng kiểm kê
activate System
System -> "Nhân viên": 3.Thông báo nhiệm vụ của nhân viên
deactivate System
"Nhân viên" -> "Nhân viên": 4. Kiểm kê tài sản

"Nhân viên" -> "System": 5.Cập nhật biên bản kiểm kê
activate System

System -> "Quản lý": 6..Gửi biên bản kiểm kê

deactivate System
@enduml
