@startuml

participant "Nhân viên" as nv


participant "Hệ thống" as System
participant "Quản lý" as ql

participant "Nhà cung cấp" as ncc
participant "Nhân viên(Kế toán)" as kt


nv -> System: 1.Tạo yêu cầu mua mới thiết bị
activate System
System --> nv: 2. Tạo hợp đồng theo mẫu
deactivate System
nv -> ql: 3. Chỉnh sửa (nếu có) và Gửi yêu cầu xác nhận
alt từ chối
    ql -> System: 4a1. Thông báo từ chối
    activate System
    System -> nv: 4a2. Gửi thông báo từ chối
else duyệt
    deactivate System
    ql -> System: 4b1. Thông báo duyệt
    activate System
    System -> nv: 4b2. Yêu cầu soạn hợp đồng
    deactivate System
    par
        nv -> ncc: 4b3. Liên hệ nhà cung cấp kí hợp đồng
        nv -> ql: 4b4. Yêu cầu kí hợp đồng
        ncc --> nv: Đã ký
        ql --> nv: Đã ký
    end
    kt -> kt: 4b5. Scan hợp đồng
    kt -> System: 4b6: Lưu thông tin
    activate System
    deactivate System
    kt -> ncc: 4b7: Thanh toán 50%
    ncc -> kt: 4b8: Bàn giao thiết bị
    kt -> ncc: 4b9: Thanh toán 50% còn lại

    kt -> System: 4b10: Xác nhận đã thanh toán toàn bộ
    activate System

    System -> ql: 4b11: Thông báo mua thành công
    deactivate System
end

deactivate System
@enduml
