@startuml

participant NhanVien

participant "Hệ thống" as System
participant "Cơ dở dữ liệu" as CSDL


NhanVien -> System: 1. Nhấn button “Thêm thông tin cư dân”
activate System
System -> System: 2. Hiển thị popup form “Thêm thông tin cư dân”
NhanVien -> System: 3. Nhập thông tin "số điện thoại" vào trường dữ liệu
System -> CSDL: 4. Kiểm tra ràng buộc

alt Tồn tại
activate CSDL
    CSDL -> CSDL: 5.Lấy tài khoản từ thông tin số điện thoại 
    CSDL -> System: 6. Fill các trường dữ liệu thông tin
    NhanVien -> System: 4a3. Nhấn “Đồng ý”
    System -> System: 4a4. Hiển thị màn hình danh sách cư dân
else Không tồn tại
    System -> System: 5b1. Hiển thị thông báo “Vui lòng điền đầy đủ các thông tin”
    NhanVien -> System: Quay lại bước 3
end

alt Exception Flow
    NhanVien -> System: 5a1. Nhấn “Thử lại/Hủy bỏ”
    System -> System: 5a2. Hiển thị popup “Thông báo lỗi. Vui lòng thử lại.”

    alt Trường hợp 2: Dữ liệu không hợp lệ
        System -> System: 5b1. Hiển thị thông báo lỗi và quay lại popup Thêm cư dân
    end

end

NhanVien -> System: Kết thúc use case
deactivate System

@enduml
