@startuml

participant "Nhân viên"

participant "Hệ thống" as System
participant "Cơ dở dữ liệu" as CSDL


"Nhân viên" -> System: 1. Chọn module "Yêu cầu dịch vụ"
activate System
System -> System: 2.Hiển thị danh sách yêu cầu dịch vụ
"Nhân viên" -> System: 3.Chọn yêu cầu dịch vụ cần xử lý
System -> System: 4.Hiển thị popup chi tiết yêu cầu dịch vụ
"Nhân viên" -> System: 5.Xác nhận yêu cầu dịch vụ
alt Xác nhận

   "Nhân viên" -> System: 5a1. Nhấn button "Đồng ý"
   System -> CSDL: 5a2. Gửi yêu cầu kiểm tra thông tin
       activate CSDL
CSDL --> System: 5a3. Hiển thị thông báo"Chấp nhận yêu cầu thành công"

        deactivate CSDL
else Không tồn tại  
    "Nhân viên" -> System: 5a2. Nhấn button "Từ chối"
    System -> CSDL: 5b1. Gửi yêu cầu kiểm tra thông tin
     activate CSDL
    CSDL--> System: 5b2. Hiển thị danh sách yêu cầu dịch vụ 
         deactivate CSDL
end

@enduml
