@startuml
left to right direction

actor Admin as C
rectangle "Quản lý tài sản" {
  usecase (CRUD thông tin tài sản) as UC1
  usecase (Theo dõi bảo trì và sửa chữa) as UC3
  usecase (CRUD lịch kiểm kê tài sản) as UC4
  (UC4)<..(Cập nhật thông tin tài sản, kết quả kiểm kê):<<extend>>
  usecase (Xem báo cáo tình trạng tài sản) as UC5
  usecase (CRUD mua sắm và thanh lý tài sản) as UC6

}
C --UC1
C--UC3
C--UC4
C--UC5
C--UC6
@enduml
