@startuml
left to right direction

actor Admin as C
actor User as U
rectangle "Quản lý ra vào" {
  usecase (CRUD thẻ hoặc mã xác nhận) as UC2
  (UC2)..>(Lấy thông tin dân cư):<<extend>>
  usecase (Xem lịch sử ra vào và ra khỏi) as UC3
  usecase (Quản lý và kiểm soát các điểm ra vào) as UC4
  usecase (Xử lý trường hợp mất mất thẻ) as UC5
  

  usecase "Yêu cầu tạo thẻ ra vào cho khách" as UC7
  usecase "Ra vào tòa nhà" as UC8
  usecase "Gửi yêu cầu hỗ trợ trường hợp mất thẻ " as UC10
}
UC7 ..> UC4:<<extend>>
C--UC2
C--UC3
C--UC4
C--UC5
UC8 ..> UC4:<<extend>>
UC5 <.. UC10:<<include>>
UC7--U
UC8--U
UC10--U



@enduml
