@startuml
left to right direction

actor Admin as C
actor Staff as S
rectangle "Website: Desktop" {
  usecase (Xác nhận ra vào và ra khỏi tòa nhà) as UC1
   (UC1)<..(Quét thẻ):<<extend>>
      (UC1)<..(Quét mã QR):<<extend>>
  usecase (CRUD thẻ hoặc mã xác nhận) as UC2
    (UC2)..>(CRUD thông tin dân cư):<<include>>
  usecase (Xem lịch sử ra vào và ra khỏi) as UC3
  usecase (Quản lý và kiểm soát các điểm ra vào) as UC4
usecase (Xử lý trường hợp mất mát thẻ hoặc mã) as UC5
    usecase (Báo cáo và thống kê về ra vào) as UC6

}

rectangle "App: Điện thoại" {
  usecase "Đặt lịch ra vào" as UC7
  usecase "Xác nhận ra vào tòa nhà" as UC8
  usecase "Xem lịch sử ra vào và ra khỏi" as UC9
  usecase "Gửi yêu cầu hỗ trợ trường hợp mất thẻ hoặc mã" as UC10
  
}

UC1 -- C
UC2 -- C
UC3 -- C
UC4 -- C
UC5 -- C
UC6 -- C
S -- UC7
S -- UC8
S -- UC9 
S -- UC10 
UC1 -- UC7
UC1 -- UC8
UC2 -- UC7
UC2 -- UC9
UC5 -- UC10



@enduml
