@startuml
left to right direction

actor Admin as C
actor Staff as S
rectangle "Website: Máy tính" {
  usecase (CRUD thông tin người bên thuê) as UC1
  usecase (CRUD thông tin căn hộ) as UC2
  usecase (CRUD thông tin thông báo) as UC3
  usecase (Xem báo cáo và thống kê) as UC4
}

rectangle "App: Điện thoại" {
  usecase "Đăng nhập" as UC5
  usecase "RU thông tin người bên thuê" as UC6
  usecase "Xem thông tin căn hộ" as UC7
  usecase "Xem thông tin thông báo" as UC8
  usecase "Xem thống kê về thanh toán" as UC9
  
}

C -- UC1
C -- UC2
C -- UC3
C -- UC4
UC5 -- S
UC6 -- S
UC7 -- S
UC8 -- S
UC9 -- S
UC1 -- UC5
UC1 -- UC6
UC2 -- UC7
UC3 -- UC8
UC4 -- UC9


@enduml
