@startuml
|Admin|
start
repeat  :Thêm;
repeat :Thêm;
if (Thêm bằng xlxs?) then (true)
    |Admin|
    :Chọn button "Excel";
    :Chọn file trong hệ thống;
else (false)
    |Admin|
    :Chọn button "Thêm";
    :Nhập thông tin căn hộ;
    |Hệ thống|
endif
repeat while (kiểm tra ràng buộc) is (không thỏa) not (thỏa)
|Cơ sở dữ liệu|
repeat while (kiểm tra tồn tại) is ( tồn tại) not (không tồn tại)
:Lưu;
|Hệ thống|
:Hiển thị thông báo "Tạo thành công;
:Tự động gửi mã căn hộ và "Hướng dẫn tải app cư dân" qua SMS sđt cho chủ hộ;
Stop
@enduml