@startuml
|Admin|
start
:Chộn bên thuê cần sửa thông tin;
|Hệ thống|
:Hiển thị màn hình sửa thông tin bên thuê;
|Admin|
repeat :Nhập thông tin cần sửa;
|Hệ thống|
repeat while (kiểm tra ràng buộc?) is (Không thỏa) not (thỏa)
|Cơ sở dữ liệu|
:Cập nhật dữ liệu;
|Hệ thống|
:Hiển thị thông báo thành công;
stop
@enduml