@startuml
|Quản lý|
start
:1. Công bố quyết định kiểm kê;
:2. Thành lập hội đồng kiểm kê;
|Nhân viên|
:3. Kiểm kê tài sản;
:4. Nhập thông tin trạng thái tài sản;
:5. Tạo biên bản kiểm kê;
:6. Gửi biên bản kiểm kê;
|Hệ thống|
:7. Lưu data;
|Quản lý|
:8. Nhận biên bản kiểm kê;
:9. Báo cáo kết quả;
stop
@enduml