@startuml
|Nhân viên|
start
:1. Tạo yêu cầu mua mới thiết bị;
:2. Điền các danh mục, giá cả, nhà cung cấp;
|Hệ thống|
:4. Tạo hợp đồng theo mẫu;
|Nhân viên|
:5. Chỉnh sửa (nếu có) và gửi yêu cầu;
|Quản lý|
if (xác nhận) then (Từ chối)
    |Hệ thống|
    :6. Thông báo nhân viên;
    stop
else (Duyệt)
    |Hệ thống|
    :7. Thông báo nhân viên;
endif
|Nhân viên|
:8. Soạn hợp đồng;
:9. Liên hệ nhà cung cấp;
fork
    |Nhà cung cấp|
    :10. Ký hợp đồng;
fork again
    |Quản lý|
    :11. Ký hợp đồng;
end fork
|Nhân viên(Kế toán)|
:12. Scan hợp đồng cho vào hệ thống;
|Hệ thống|
:13. Lưu thông tin;
|Nhân viên(Kế toán)|
:14. Thanh toán 50%;
|Nhà cung cấp|
:15. Bàn giao thiết bị;
|Nhân viên(Kế toán)|
:16. Thanh toán 50%;
|Hệ thống|
:17. Thông báo quản lý;
stop
@enduml