@startuml
|Nhân viên|
|Cư dân|
start
:1. Gửi yêu cầu bảo trì;
|Nhân viên|
:2. Nhận yêu cầu bảo trì;
:3. Xác nhận thông tin bảo trì;
if (Đồng ý bảo trì?) then (không đồng ý)
    :4. Ghi lý do;
    |Hệ thống|
    :5. Thông báo Cư dân;
    |Cơ sở dữ liệu|
    :6. Lưu data;
    stop
else (Đồng ý)
    |Nhân viên|
    :7. Chọn nhân sự bảo trì;
    :8. Đặt công cụ bảo trì ở phòng quản lý thiết bị;
    repeat :9. Đặt lịch ngày bảo trì;
    |Hệ thống|
    repeat while (Thiết bị, nhân sự) is (không sẵn sàng vào ngày bảo trì) not ( sẵn sàng vào ngày bảo trì)
    :10. Thông báo Cư dân và nhân viên;
    |Cơ sở dữ liệu|
    :11. Lưu data;
    stop
endif
@enduml