@startuml
|Nhân viên|
start
:1. Kiểm tra tài sản;
:2. Thêm vào danh sách thanh lý;
:3. Thông báo Quản lý;
|Quản lý|
if (duyệt thanh lý từng tài sản) then (không đồng ý)
    |Hệ thống|
    :4. Thông báo nhân viên danh sách tài sản không được duyệt;
else (Đồng ý)
    :5. Thông báo nhân viên tài sản được duyệt;
endif
|Nhân viên (Kế toán)|
:6. Thanh lý;
:7. Nhập số tiền và giá tiền mỗi tài sản thanh lý được;
stop
@enduml