@startuml
|Quản lý|
:1. Chọn hợp đồng;
:2. Tạo yêu cầu gia hạn hợp đồng;
:3. Chọn thời hạn;
|Hệ thống|
:4. Gửi hợp đồng cho đối tác;
|Cư dân|
:. Nhận thông tin;
if (Kiểm tra thông tin) then (Không chấp nhận)
|Hệ thống|
:6. Gửi thông báo yêu cầu đã bị từ chối cho Quản lý;
stop
else (Chấp nhận)
endif
:7. Gửi thông báo chấp nhận cho Quản lý;
fork
|Quản lý|
:8. Ký eSignature;
fork again
|Cư dân|
:9. Ký eSignature;
end fork
|Hệ thống|
:10. Lưu data;
:11. Thông báo 2 bên gia hạn hợp đồng thành công qua email;
stop
@enduml