@startuml
|Admin|
:Chọn hợp đồng;
:Tạo yêu cầu gia hạn hợp đồng;
:Chọn thời hạn;
|Hệ thống|
:Gửi hợp đồng cho đối tác;
|Partner|
:Nhận thông tin;
if (Kiểm tra thông tin) then (Không chấp nhận)
|Hệ thống|
:Gửi thông báo yêu cầu đã bị từ chối cho Admin;
stop
else (Chấp nhận)
endif
:Gửi thông báo chấp nhận cho Admin;
fork
|Admin|
:Ký eSignature;
fork again
|Partner|
:Ký eSignature;
end fork
|Hệ thống|
:Lưu data;
:Thông báo 2 bên gia hạn hợp đồng thành công;
stop
@enduml