@startuml
|User1|
start
:Chọn hợp đồng;
:Tạo yêu cầu kết thúc hợp đồng/hoàn cọc;
|Hệ thống|
if(Kiểm tra thông tin) then (Không hợp lệ)
:Từ chối;
stop
else(Hợp lệ)
endif
:Yêu cầu xác nhận lại thông tin;
|User1|
:Xác nhận;
|Hệ thống|
:Gửi thông báo cho User2;
|User2|
if(Đồng ý) then (Không đồng ý)
|Hệ thống|
:Chuyển thông báo cho User1;
stop
else (Hợp lệ)
endif
:Thông báo User1;
:Lưu data;
stop
@enduml