@startuml
|Quản lý|
start
:1. Tạo hợp đồng;
:2. Chọn bản mẫu hoặc tải tệp tin lên;
repeat :3. Điền các thông tin cần\n thay đổi/thông tin mới;
:4. Nhấn "Tạo";
|Hệ thống|
repeat while (Kiểm tra các ràng buộc) is (Không hợp lệ) not (Hợp lệ)
:5. Tạo bản word theo yêu cầu;
:6. Lưu data;
stop
@enduml