@startuml

|Nhanvien|
start
:Chọn module "Quản lý thu phí";
:Chọn "Thông báo phí";
|Website Nhanvien|
:Hiển thị danh sách thông báo thu phí;
|Nhanvien|
:Chọn button "Tạo thông báo phí";
|Website Nhanvien|
repeat
:Hiển thị popup "Tạo thông báo phí";
|Nhanvien|
:Nhập thông tin thông báo phí và nhấn "Gửi thông báo";
|Website Nhanvien|
repeat while (Gửi thành công?) is (no) not (yes);
:Hiển thị thông báo "Gửi thông báo thu phí thành công";
stop
@enduml